# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 36a471fdf0e2a1f63d739bd99d886022b1bf5cb2fdbb583850fd879c2ddb7d0b8f160d437c784989678ddf52c6b83f8b5ac2dcf8ea7631da035cb7f479098462

test:
  secret_key_base: 0508f3881928422e45d3066fae7fb1a1d3cf5131ceff21726031c3201f91a7ec99cc65d57e09b8ae870d63bd8a15c51497f124ccbc72e522dce94a91bc6a347e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
